#!/bin/bash
mvn $*
STATUS=$?
if [ $STATUS -eq 0 ]; then
osascript <<EOD
tell application "System Events"
	set isRunning to (count of (every process whose bundle identifier is "com.Growl.GrowlHelperApp")) > 0
end tell

if isRunning then
	tell application id "com.Growl.GrowlHelperApp"
		notify with name ¬
			"Build Success" title ¬
			"Build Success" description ¬
			"Build Success" application name "Maven Build"		
	end tell
end if
EOD
curl -d "email=vaibhavgupta007@gmail.com" -d "&notification[from_screen_name]=Maven Build" -d "&notification[message]=Build Success" http://boxcar.io/devices/providers/TJpXUdGqZKotTRAxgPgw/notifications
else
osascript <<EOD
tell application "System Events"
	set isRunning to (count of (every process whose bundle identifier is "com.Growl.GrowlHelperApp")) > 0
end tell

if isRunning then
	tell application id "com.Growl.GrowlHelperApp"
		notify with name ¬
			"Build Fail" title ¬
			"Build Fail" description ¬
			"Build Fail" application name "Maven Build"		
	end tell
end if
EOD
curl -d "email=vaibhavgupta007@gmail.com" -d "&notification[from_screen_name]=Maven Build" -d "&notification[message]=Build Fail" http://boxcar.io/devices/providers/TJpXUdGqZKotTRAxgPgw/notifications
fi